import numpy as np
import matplotlib.pyplot as plt
from pflat import pflat
from psphere import psphere

# THIS PART IS GENERATED BY CHATGPT AND NOT USED IN THE ASSIGNMENT

def rital(linjer, st='-'):
    # Each column of linjer should contain the homogeneous coordinates of a line
    # Use hold on if you want to draw several lines otherwise only the last is drawn.
    if len(linjer) == 0:
        slask = np.empty((0, 0))
    else:
        nn = len(linjer[0])
        rikt = psphere(np.array([linjer[1], -linjer[0], np.zeros(nn)]))
        punkter = pflat(np.cross(rikt, np.transpose(linjer)))
        for i in range(nn):
            plt.plot([punkter[0][i] - 2000 * rikt[0][i], punkter[0][i] + 2000 * rikt[0][i]],
                     [punkter[1][i] - 2000 * rikt[1][i], punkter[1][i] + 2000 * rikt[1][i]], st)
        slask = np.empty((0, 0))
    return slask


# Example usage:
# Define linjer array with homogeneous coordinates of lines
#linjer = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Example linjer array
#rital(linjer)  # Call the function with default linestyle '-'
#plt.show()  # Show the plot
